### ISSUE TITLE
一些问题

### ISSUE THREAD

**Issue by Edfgdz** [ekibun/Stitch#1]
1.这四张图片用stitch拼接的时候会出现问题

![Screenshot_2021-11-08-19-15-42-930_com android vending](https://user-images.githubusercontent.com/26460124/141082638-37a36262-cb42-45af-aab3-c46412afcb16.jpg)

![Screenshot_2021-11-08-19-15-47-608_com android vending](https://user-images.githubusercontent.com/26460124/141082661-3f5c03c1-6b65-45e2-87cb-c12f99a9f550.jpg)

![Screenshot_2021-11-08-19-15-52-926_com android vending](https://user-images.githubusercontent.com/26460124/141082699-2f350386-3ee1-4137-ac2c-f63ccc2384bd.jpg)

![Screenshot_2021-11-08-19-15-58-043_com android vending](https://user-images.githubusercontent.com/26460124/141082721-e63bc5b6-dbeb-4ffb-94e6-9e505286b9cb.jpg)

用stitch会拼接成这个样子

![Stitch17cff47df48](https://user-images.githubusercontent.com/26460124/141082873-5831902a-d76f-4319-ba01-fe06792e0da4.png)

而用这个软件拼接的时候能够拼接正常

![result-2021-11-08-19-17-31](https://user-images.githubusercontent.com/26460124/141083373-76eb12da-0c9b-4ab4-a08f-b9961025dd84.png)

图片拼接PPIICC(bos.consoar.imagestitch) - 0.4.6 - 应用 - 酷安 
https://www.coolapk.com/apk/bos.consoar.imagestitch

所以希望开发者能看一下

2.在导入之后的操作界面，也就是这个界面，用户再次按导入按钮来导入图片的时候，希望可以把之前导入的图片清除掉，也就是第二次导入的时候只显示第二次所导入的图片，之前导入的不算

![Screenshot_2021-11-10-17-08-06-090_soko ekibun stitch](https://user-images.githubusercontent.com/26460124/141083965-3a9ed96f-52c9-4c72-8133-a0240cab581f.jpg)

**Comment by ekibun** [comment]
算法就是这样，你这重合区域太小了，PPIICC不开源抄不到代码

**Comment by ekibun** [comment]
导入图片设计上就是增量的，要删掉可以全选删除，改成覆盖就没办法实现增量了

**Comment by ekibun** [comment]
额怎么说呢，我测试上PPIICC也有很多拼不对的，算法上目前这个是比较快的了，你可以试试前一个版本的算法，那个慢一点但是应该能适应更小的重合位置。
而且目前这个算法能支持任意方向，这也是其他拼接app没做的，开源的也不多，不方便借鉴

**Comment by Edfgdz** [comment]
用老版本发现的确能拼接成功

**Comment by ekibun** [comment]
那以后加上设置选算法吧，原算法还是太慢了

**Comment by Edfgdz** [comment]
有没有办法在既保证速度的情况下又拼接正确？

**Comment by ekibun** [comment]
没有，有我就直接用了
