### ISSUE TITLE
Privacy policy in English, policy should not limit license freedoms

### ISSUE THREAD

**Issue by licaon-kter** [ekibun/Stitch#5]
ref: https://ekibun.github.io/Stitch/v2/privacy

It's great that the app is now in F-Droid, but the very first screen will make people go away if they have to agree to a Privacy policy that they can't (easily) read.

After translation please include this in the actual app so users don't need to connect to proprietary Github services just to read a bit of text.

Also, this feels really odd, statements like _"We will use your personal information in accordance with the Network Security Law of the People's Republic of China, the Code of Personal Information Security for Information Security Technology and other relevant laws and regulations, proven security standards in the industry and as agreed in this agreement."_ seem off-putting, so even if the app has no Internet access you'll still collect the information? If no information is collected then why bother saying otherwise?

_"Users may not use the software-related services to create, publish, reproduce, transmit, distribute or store information that"_... which constitution? Which law? Is it okay if it's legal in my country but not in yours? If I stitch a meme does that count as _"Disseminating rumours"_?

That being said, the actual [app license](https://github.com/ekibun/Stitch/blob/master/LICENSE) grants users the freedom to run this app as they fit, not sure you can just put a policy on top that might negate those to begin with.

Thanks

**Comment by licaon-kter** [comment]
fyi https://gitlab.com/fdroid/fdroiddata/-/issues/2894 :(

**Comment by ekibun** [comment]
Privacy policy removed

**Comment by licaon-kter** [comment]
Will take a look asap
